version: '3'
services:
    dev:
        tty: true
        build:
            context: .devcontainer
            dockerfile: Dockerfile
        image: synerex_server
        environment:
            - SX_SERVER_HOST=server
        ports:
            - "10000:10000"